development: &default
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  pool: 5
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: demo_app_test